version: '3'

services: 
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      - API_LOCATION=http://localhost:3001

  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:  
      - PORT=3001
    ports:
      - 3001:3001
